# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rx-blocking-test-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for rx-blocking-test-ios
  pod 'RxSwift'
  pod 'RxBlocking'
  pod 'RxTest'

  target 'rx-blocking-test-iosTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift'
    pod 'RxBlocking'  
    pod 'RxTest' 
end

  target 'rx-blocking-test-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
